// Package interchange writes preserved message bytes out in the standard mail
// interchange formats a migration target understands: mboxrd (one file per
// folder) and byte-exact .eml (one file per message). It only ever copies bytes
// that were preserved at capture (`-raw`); it never re-serializes or synthesizes
// a message, so nothing it writes is a forgery.
//
// The mbox flavour is mboxrd (design G4/PC12): each message is preceded by a
// synthesized "From " postmark and every body line matching `>*From ` is
// `>`-quoted. A reader that unquotes `>From ` recovers the exact original bytes;
// an mboxo reader does not; for a consumer of unknown flavour, `-format eml` is
// the byte-exact format.
package interchange

import (
	"bytes"
	"fmt"
	"io"
	"strings"
	"time"
)

// fromPrefix is the mbox message-boundary marker: a line beginning with
// "From " (at column 0) starts a new message. mboxrd quotes any body line that
// is a run of '>' followed by "From " so it can never be mistaken for a
// boundary, and un-quotes it on the way back.
const fromPrefix = "From "

// isFromQuoteLine reports whether line (a single body line, without its trailing
// newline) is `>*From ` — the set of lines mboxrd must `>`-quote so a genuine
// boundary is unambiguous.
func isFromQuoteLine(line []byte) bool {
	i := 0
	for i < len(line) && line[i] == '>' {
		i++
	}
	return bytes.HasPrefix(line[i:], []byte(fromPrefix))
}

// WriteMessage writes one message to w in mboxrd form: a synthesized "From "
// postmark line derived from the message's own From/Date headers, the raw bytes
// with every `>*From ` line `>`-quoted, and a trailing blank line so the next
// postmark starts a clean boundary. Line endings in raw are preserved verbatim
// (a CRLF message stays CRLF); a final line with no newline is terminated with
// one so the blank-line separator is unambiguous. It returns any write error
// from w so the caller can discard a torn temp file (ENOSPC) and refuse.
func WriteMessage(w io.Writer, raw []byte) error {
	if _, err := io.WriteString(w, Postmark(raw)); err != nil {
		return err
	}
	if _, err := io.WriteString(w, "\n"); err != nil {
		return err
	}
	i := 0
	for i < len(raw) {
		j := bytes.IndexByte(raw[i:], '\n')
		var line []byte
		if j < 0 {
			line = raw[i:]
			i = len(raw)
		} else {
			line = raw[i : i+j]
			i += j + 1
		}
		if isFromQuoteLine(line) {
			if _, err := io.WriteString(w, ">"); err != nil {
				return err
			}
		}
		if _, err := w.Write(line); err != nil {
			return err
		}
		if _, err := io.WriteString(w, "\n"); err != nil {
			return err
		}
	}
	// The blank line that separates this message from the next postmark.
	_, err := io.WriteString(w, "\n")
	return err
}

// Postmark synthesizes the "From " postmark line for a message from its own
// header block: the address from the first From: header and the time from the
// first Date: header, both parsed leniently. It never fails — an unparseable or
// absent header falls back to a stable placeholder ("MAILER-DAEMON" / the Unix
// epoch) so the output is deterministic (a re-run produces identical bytes) and
// a malformed message can still be framed (R10). The postmark's only job is to
// mark a boundary; its content is not part of the preserved message.
func Postmark(raw []byte) string {
	addr := headerAddress(firstHeader(raw, "from"))
	if addr == "" {
		addr = "MAILER-DAEMON"
	}
	when := time.Unix(0, 0).UTC()
	if d := firstHeader(raw, "date"); d != "" {
		if t, err := parseDate(d); err == nil {
			when = t.UTC()
		}
	}
	// asctime form, as generated by mbox writers: "Mon Jan _2 15:04:05 2006".
	return fmt.Sprintf("%s%s %s", fromPrefix, addr, when.Format("Mon Jan _2 15:04:05 2006"))
}

// parseDate parses an RFC 5322 Date header, accepting the common variants
// (with and without a leading weekday, numeric or named zone).
func parseDate(v string) (time.Time, error) {
	v = strings.TrimSpace(v)
	layouts := []string{
		"Mon, 2 Jan 2006 15:04:05 -0700",
		"Mon, 2 Jan 2006 15:04:05 MST",
		"2 Jan 2006 15:04:05 -0700",
		"2 Jan 2006 15:04:05 MST",
		time.RFC1123Z,
		time.RFC1123,
	}
	var firstErr error
	for _, l := range layouts {
		if t, err := time.Parse(l, v); err == nil {
			return t, nil
		} else if firstErr == nil {
			firstErr = err
		}
	}
	return time.Time{}, firstErr
}

// firstHeader returns the unfolded value of the first occurrence of the named
// header (case-insensitive) in raw's header block — the bytes up to the first
// blank line. It stops at the header/body boundary so a body line that looks
// like a header is never read. Returns "" when the header is absent.
func firstHeader(raw []byte, name string) string {
	lname := strings.ToLower(name)
	i := 0
	for i < len(raw) {
		j := bytes.IndexByte(raw[i:], '\n')
		var line []byte
		if j < 0 {
			line = raw[i:]
			i = len(raw)
		} else {
			line = raw[i : i+j]
			i += j + 1
		}
		trimmed := bytes.TrimRight(line, "\r")
		if len(trimmed) == 0 {
			break // end of the header block
		}
		colon := bytes.IndexByte(trimmed, ':')
		if colon < 0 {
			continue
		}
		if strings.ToLower(string(trimmed[:colon])) != lname {
			continue
		}
		value := string(bytes.TrimSpace(trimmed[colon+1:]))
		// Fold any continuation lines (leading whitespace) into the value.
		for i < len(raw) {
			k := bytes.IndexByte(raw[i:], '\n')
			var next []byte
			if k < 0 {
				next = raw[i:]
			} else {
				next = raw[i : i+k]
			}
			nt := bytes.TrimRight(next, "\r")
			if len(nt) == 0 || (nt[0] != ' ' && nt[0] != '\t') {
				break
			}
			value += " " + string(bytes.TrimSpace(nt))
			if k < 0 {
				i = len(raw)
			} else {
				i += k + 1
			}
		}
		return value
	}
	return ""
}

// headerAddress extracts a bare email address from a From header value
// ("Name <a@b>" → "a@b"; "a@b" → "a@b"), control-stripped so the postmark line
// stays a single clean line. Returns "" when no plausible address is present.
func headerAddress(v string) string {
	if lt := strings.LastIndexByte(v, '<'); lt >= 0 {
		if gt := strings.IndexByte(v[lt+1:], '>'); gt >= 0 {
			v = v[lt+1 : lt+1+gt]
		}
	}
	v = strings.TrimSpace(v)
	// A postmark address is a single token with no whitespace or controls; if
	// what remains is not one, drop it rather than emit a broken boundary line.
	if v == "" || strings.ContainsAny(v, " \t\r\n") {
		return ""
	}
	for _, r := range v {
		if r < 0x20 || r == 0x7f {
			return ""
		}
	}
	return v
}
